export const SETUP_TIME = "SETUP_TIME";
export const SETUP_TIME_SUCCESS = "SETUP_TIME_SUCCESS";

export const START_CRAWL_DATA = "START_CRAWL_DATA";

export const GET_NUMBER_INFORMATION = "GET_NUMBER_INFORMATION";
export const GET_NUMBER_INFORMATION_SUCCESS = "GET_NUMBER_INFORMATION_SUCCESS";

export const GET_LENGHT_LIST = "GET_LENGHT_LIST";